#!/usr/bin/env ruby
# http://bit.ly/ url the clipboard on OSX

%w[uri cgi rubygems json].each {|l| require l }
%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

output = ''

class BitlyError < Exception; end

begin
  encoded_url = clipboard.match(/^http/) ? clipboard : "http://#{clipboard}" 
  encoded_url = URI.parse(URI.encode(encoded_url)).normalize.to_s

  curl_url_json = `curl --stderr /dev/null \"http://api.bit.ly/shorten?longUrl=#{ CGI.escape(encoded_url) }&version=2.0.1&login=yourbitlylogin&apiKey=yourbitlyapikey&history=1\"`
  bitly_result = JSON.parse(curl_url_json)

  if bitly_result["results"]
    output = bitly_result["results"].values.first["shortUrl"]
  else
    raise BitlyError, bitly_result.collect {|k,v| "#{k}:#{v}" }.join('; ')
  end
  self.clipboard = notify(output)
rescue Exception => e
  notify("# Failed, sorry: #{e.message}")
end
