#!/bin/bash
# Downcase the contents of the macOS clipboard

set -euo pipefail
LIB="$(dirname "$(readlink -f "$0")")/lib"

RESULT="$(/usr/bin/pbpaste | tr '[:upper:]' '[:lower:]')"
printf '%s' "$RESULT" | /usr/bin/pbcopy
"$LIB/notify" --from "$(basename "$0")" -- "$RESULT"
