#!/usr/bin/env ruby
# decode Google search links to get destination url

GOOGLE_LINK_RE = %q[https?://www.google.com(?:\...)?/url\?.*(?:url|q)=(https?(?:%3A%2F%2F|://)[^&]+)]
# https://www.google.com/url?q=http://lesswrong.com/lw/jg/planning_fallacy/&sa=U&ei=G6ulUf-LComYqAHbuIDQCQ&ved=0CAcQFjAA&client=internal-uds-cse&usg=AFQjCNFnb1OtVL1uuIiuvTnjaqOaqsraxQ
# https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&ved=0CDAQFjAA&url=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPlanning_fallacy&ei=_qulUbTqOMmCiQfbx4CYCw&usg=AFQjCNGFtR1K-hSLR-8aeW0EowOGhDcuSQ&sig2=NXIWMQfEp9nMCDLgSwLuTw&bvm=bv.47008514,d.aGc
# https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiZsbLPsdzJAhWDIqYKHZhLBqgQFgglMAA&url=https%3A%2F%2Fwww.givedirectly.org%2F&usg=AFQjCNFSnkTpUyRj51TbStjpwPw_dRa3aQ&sig2=ReCY5wIG7CbCuYM_ajaJtA

require 'uri'
%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

if clipboard.match(Regexp.new(GOOGLE_LINK_RE))
  clipboard { URI.decode($1) }
else
  notify("That doesn't look like a Google search URL.")
end
