#!/usr/bin/env ruby
# URI escape the contents of the OSX clipboard

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"
require 'uri'

clipboard {|c| URI.escape(c) }
