#!/usr/bin/env ruby -w

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

system("osascript #{File.expand_path(File.join(File.dirname(__FILE__), "../lib/copy-finder-path.scpt"))}")
clipboard do |c|
  c.gsub(/\/Users\/.*?\//, '~/').gsub(/~\/Dropbox( \([^)]+?\))?\//, 'Dropbox:').gsub(/~\/Google Drive( \([^)]+?\))?\//, 'Google Drive:')
end
