#!/usr/bin/env ruby -w

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

system(File.expand_path(File.join(File.dirname(__FILE__), "../lib/finder-path.bash")))
notify clipboard
