#!/usr/bin/env ruby

# Convert the contents of the clipboard to textile (with
# https://github.com/jystewart/html2textile and send it to STDOUT

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"
%w[rubygems html2textile].each {|l| require l }

clipboard(true) do |c|
  parser = HTMLToTextileParser.new
  parser.feed(c)
  parser.to_textile
end
