#!/usr/bin/env ruby
# Sentence caserize the contents of the OSX clipboard
%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"
require "humanize"

clipboard {|c| HumanizingString.new(c).humanize }
