#!/usr/bin/env ruby
# Add some lorem ipsum to the OSX clipboard

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

clipboard { `/usr/bin/env lorem 1` }
