#!/usr/bin/env ruby
# MD5 hasherize the contents of the OSX clipboard

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"
require 'digest/md5'

clipboard {|c| Digest::MD5.hexdigest(c) }
