#!/usr/bin/env ruby
# Growl notify the current content of the clipboard

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

notify(clipboard, true)
