#!/usr/bin/env ruby
# Growl notify the current content of the clipboard

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

LONG_MESSAGE_LENGTH = 100

sticky = clipboard.size > LONG_MESSAGE_LENGTH
notify(clipboard, sticky)
