#!/usr/bin/env ruby
%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

PWGEN_COMMAND = %w[/usr/local/bin/pwgen /opt/local/bin/pwgen].find {|p| File.file?(p) }
PWGEN_LENGTH = 20

# put a new pw in the clipboard without looking at it
system("#{PWGEN_COMMAND} #{PWGEN_LENGTH} -1 | tr -d \"\\n\" | pbcopy")

notify("New password in clipboard", false)

# vi: filetype=ruby
