#!/usr/bin/env ruby
# Clipboard a random number

begin
  require_relative("../lib/helper")
rescue
  require File.join(File.dirname(__FILE__), "../lib/helper")
end

clipboard do |c|
  if ARGV.empty?
    rand(999999) + 1
  else
    rand(ARGV.first.to_i) + 1
  end
end
