#!/bin/bash
# ROT47-encode the contents of the clipboard

set -euo pipefail
LIB="$(dirname "$(readlink -f "$0")")/lib"

RESULT="$(/usr/bin/pbpaste | tr '!-~' 'P-~!-O')"
printf '%s' "$RESULT" | /usr/bin/pbcopy
"$LIB/notify" --from "$(basename "$0")" -- "$RESULT"
