#!/usr/bin/env ruby
# Clipboard a random number

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

clipboard do |c|
  if ARGV.empty?
    rand(999999) + 1
  else
    rand(ARGV.first.to_i) + 1
  end
end
