#!/usr/bin/env ruby
# ROT13 the contents of the OSX clipboard

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

class String
  def rot13
    self.tr('a-zA-Z','n-za-mN-ZA-M')
  end
end

clipboard(true) {|c| c.rot13 }
