#!/usr/bin/env ruby
# Remove spaces from the clipboard on OSX

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

clipboard {|c| c.gsub(/ /,"") }
