#!/bin/bash
# SHA256-hash the contents of the clipboard

set -euo pipefail
LIB="$(dirname "$(readlink -f "$0")")/lib"

RESULT="$(/usr/bin/pbpaste | /usr/bin/shasum -a 256 | cut -d' ' -f1)"
printf '%s' "$RESULT" | /usr/bin/pbcopy
"$LIB/notify" "$RESULT"
