#!/bin/bash
# Strip newlines from the clipboard

set -euo pipefail
LIB="$(dirname "$(readlink -f "$0")")/lib"

RESULT="$(/usr/bin/pbpaste | tr -d '\n')"
printf '%s' "$RESULT" | /usr/bin/pbcopy
"$LIB/notify" "$RESULT"
