#!/usr/bin/env ruby
# Title caserize the contents of the OSX clipboard

require File.join(File.dirname(__FILE__), "../lib/helper")

clipboard do |c|
  output = ""
  c.each("\s") {|w| output << w.capitalize}
  output
end
