#!/usr/bin/env ruby
# Title caserize the contents of the OSX clipboard

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

clipboard do |c|
  c.split("\s").collect {|w| w.capitalize}.join(" ")
end
