#!/usr/bin/env ruby
# Un-Dasherize the clipboard on OSX

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

clipboard do |c|
  c.gsub(/[-_]/," ").gsub(/^ +| +$/,"")
end
