#!/usr/bin/env ruby
# Quoted-printable unescape the contents of the OSX clipboard

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

class String
  def to_quoted_printable(*args)
    [self].pack("M").gsub(/\n/, "\r\n")
  end
  def from_quoted_printable
    self.gsub(/\r\n/, "\n").unpack("M").first
  end
end

clipboard do |c|
  c.from_quoted_printable
end
