#!/bin/bash
# Upcase the contents of the macOS clipboard

set -euo pipefail
LIB="$(dirname "$(readlink -f "$0")")/lib"

RESULT="$(/usr/bin/pbpaste | tr '[:lower:]' '[:upper:]')"
printf '%s' "$RESULT" | /usr/bin/pbcopy
"$LIB/notify" "$RESULT"
