#!/usr/bin/env ruby
# Underscore the clipboard on OSX

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

clipboard do |c|
  c.gsub(/[\W_]/,"_").gsub(/-+/,"_").gsub(/^_+|_+$/,"")
end
