#!/bin/sh
PATH=/usr/local/bin:/opt/local/bin:$PATH

# remove any special formatting from the contents of the OSX clipboard
pbpaste | pbcopy
/usr/bin/env growlnotify -a Quicksilver -t "Clipboard:" -m "`pbpaste`"
