#!/usr/bin/env ruby
# HTML encode the contents of the OSX clipboard
# WARNING: this pretty much doesn't work - I guess that pbcopy isn't cooperating

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"
%w[rubygems htmlentities].each {|l| require l }

clipboard do |c|
  HTMLEntities.new.decode(c)
end
