#!/usr/bin/env ruby
# CGI unescape the contents of the OSX clipboard

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"
require 'cgi'

clipboard do |c|
  CGI.unescape(c)
end
