#!/usr/bin/env ruby
# URI unescape the contents of the OSX clipboard

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"
require 'uri'

clipboard do |c|
  URI.unescape(c)
end
