#!/usr/bin/env ruby
# Word count the clipboard on OSX

%w[../lib ./lib].each {|l| $LOAD_PATH.unshift("#{File.dirname(File.expand_path(__FILE__))}/#{l}") }
require "helper"

chars = clipboard.size
words = clipboard.scan(/[\w-]+/).size
notify("#{chars} characters\n(#{words} words)")
