#!/usr/bin/env ruby
# Word count the clipboard on OSX
require File.join(File.dirname(__FILE__), "../lib/helper")

chars = clipboard.size
words = clipboard.scan(/[\w-]+/).size
notify("#{words} words\n(#{chars} characters)")
